project:
  type: website
  output-dir: docs

website:
  title: "Marc Wenzlawski - Blog"
  navbar:
    right:
      - text: Home
        href: https://wenzlawski.github.io
      - about.qmd
      - icon: github
        href: https://github.com/wenzlawski
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: simplex
      dark: cyborg
    css: styles.scss
    toc: true



