project:
  type: website
  output-dir: docs

website:
  title: "Marc Wenzlawski - Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wenzlawski
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: simplex
    css: styles.css



